//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionAgenteServicio.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int clin_cliente_id { get; set; }
        public string clvc_nombre { get; set; }
        public string clvc_apellido { get; set; }
        public string clvc_nit { get; set; }
        public string clvc_direccion { get; set; }
        public string clvc_email { get; set; }
        public Nullable<System.DateTime> cldt_fecha_nac { get; set; }
        public Nullable<System.DateTime> cldt_fecha_registro { get; set; }
        public string clvc_user_registro { get; set; }
        public Nullable<System.DateTime> clvc_fecha_modif { get; set; }
        public string clvc_user_modif { get; set; }
        public Nullable<sbyte> clbt_activo { get; set; }
    }
}
