//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionAgenteServicio.ModeloFactAdmin
{
    using System;
    
    public partial class CREDENCIALES
    {
        public string IP { get; set; }
        public string USUARIO { get; set; }
    }
}
