//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionAgenteServicio.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class formularios
    {
        public int foin_formulario_id { get; set; }
        public Nullable<int> roin_rol_id { get; set; }
        public string fovc_nombre_form { get; set; }
        public string fovc_url { get; set; }
        public Nullable<bool> fobt_edit { get; set; }
        public Nullable<bool> fobt_delete { get; set; }
        public Nullable<bool> fobt_view { get; set; }
        public System.DateTime fodt_fecha_insert { get; set; }
        public string fovc_user_insert { get; set; }
        public Nullable<System.DateTime> fodt_fecha_update { get; set; }
        public string fovc_user_update { get; set; }
        public bool fobt_is_hidden { get; set; }
    }
}
