//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionAgenteServicio.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int prin_producto_id { get; set; }
        public Nullable<int> cain_categoria_id { get; set; }
        public string prvc_nombre_producto { get; set; }
        public Nullable<decimal> prdc_precio_producto { get; set; }
    }
}
