//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentacionAgenteServicio.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string usvc_usuario_id { get; set; }
        public string usvc_nombre_usuario { get; set; }
        public string usvc_contraseña_usuario { get; set; }
        public Nullable<System.DateTime> usdt_fecha_registro { get; set; }
        public string usvc_user_registro { get; set; }
        public Nullable<System.DateTime> usdt_fecha_modif { get; set; }
        public string usvc_user_modif { get; set; }
        public Nullable<bool> usbt_activo { get; set; }
    }
}
